app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8081'

logger:
  log_level: 'debug'

postgres:
  url: '127.0.0.1'
  pool_max: 2

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'
  url: '127.0.0.1'
